<?php

/**
 * WeActivity
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:48
 */
class WeActivity extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=128, nullable=false)
     */
    public $act_title;

    /**
     *
     * @var string
     * @Column(type="string", length=128, nullable=true)
     */
    public $act_img;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $act_desc;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $status;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $time_start;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $time_end;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $is_allcom;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $send_money;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $send_act;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $time_instert;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $time_edit;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    public $send_money_to_channel;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $act_type;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeActivity[]|WeActivity|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeActivity|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'act_title' => 'act_title',
            'act_img' => 'act_img',
            'act_desc' => 'act_desc',
            'status' => 'status',
            'time_start' => 'time_start',
            'time_end' => 'time_end',
            'is_allcom' => 'is_allcom',
            'send_money' => 'send_money',
            'send_act' => 'send_act',
            'time_instert' => 'time_instert',
            'time_edit' => 'time_edit',
            'send_money_to_channel' => 'send_money_to_channel',
            'act_type' => 'act_type'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_activity';
    }

}
