<?php

/**
 * WeAdvert
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:49
 */
class WeAdvert extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $classid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $url;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $readme;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $strcode;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $time1;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $time2;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $cls;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $img1;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $img2;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $flash;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $isuse;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $other;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeAdvert[]|WeAdvert|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeAdvert|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'classid' => 'classid',
            'title' => 'title',
            'url' => 'url',
            'readme' => 'readme',
            'strcode' => 'strcode',
            'time1' => 'time1',
            'time2' => 'time2',
            'cls' => 'cls',
            'img1' => 'img1',
            'img2' => 'img2',
            'flash' => 'flash',
            'isuse' => 'isuse',
            'other' => 'other'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_advert';
    }

}
