<?php

/**
 * WeAdminLog
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:49
 */
class WeAdminLog extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $level;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=true)
     */
    public $action;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=true)
     */
    public $action_name;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $uid;

    /**
     *
     * @var string
     * @Column(type="string", length=30, nullable=true)
     */
    public $uname;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $time_int;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $time;

    /**
     *
     * @var string
     * @Column(type="string", length=16, nullable=true)
     */
    public $ip;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $server_data;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $get_data;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $post_data;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $desc;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeAdminLog[]|WeAdminLog|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeAdminLog|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'level' => 'level',
            'action' => 'action',
            'action_name' => 'action_name',
            'uid' => 'uid',
            'uname' => 'uname',
            'time_int' => 'time_int',
            'time' => 'time',
            'ip' => 'ip',
            'server_data' => 'server_data',
            'get_data' => 'get_data',
            'post_data' => 'post_data',
            'desc' => 'desc'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_admin_log';
    }

}
