<?php

/**
 * WeArea
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:50
 */
class WeArea extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $ic;

    /**
     *
     * @var string
     * @Column(type="string", length=11, nullable=true)
     */
    public $szcode;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $pinyin;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    public $citymark;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $pid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $isleaf;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $idpath;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $idpathv;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $mytype;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $myclass;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $depth;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $content;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $isopen;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $isuse;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $cls;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $iscentercity;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $ishot;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $longitude;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $latitude;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeArea[]|WeArea|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeArea|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'ic' => 'ic',
            'szcode' => 'szcode',
            'title' => 'title',
            'pinyin' => 'pinyin',
            'citymark' => 'citymark',
            'pid' => 'pid',
            'isleaf' => 'isleaf',
            'idpath' => 'idpath',
            'idpathv' => 'idpathv',
            'mytype' => 'mytype',
            'myclass' => 'myclass',
            'depth' => 'depth',
            'content' => 'content',
            'isopen' => 'isopen',
            'isuse' => 'isuse',
            'cls' => 'cls',
            'iscentercity' => 'iscentercity',
            'ishot' => 'ishot',
            'longitude' => 'longitude',
            'latitude' => 'latitude'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_area';
    }

}
