<?php

/**
 * WeBbsCom
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:51
 */
class WeBbsCom extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=false)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $content;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $uid;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $etime;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $endtime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $issue_status;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $comlist;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $level;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $type;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeBbsCom[]|WeBbsCom|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeBbsCom|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'title' => 'title',
            'content' => 'content',
            'uid' => 'uid',
            'stime' => 'stime',
            'etime' => 'etime',
            'endtime' => 'endtime',
            'issue_status' => 'issue_status',
            'comlist' => 'comlist',
            'level' => 'level',
            'type' => 'type'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_bbs_com';
    }

}
