<?php

/**
 * WeCheckorder
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:52
 */
class WeCheckorder extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $checkcontentid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $orderid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $title;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $duid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $dnick;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $allprice;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $commission;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $myfromname;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeCheckorder[]|WeCheckorder|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeCheckorder|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'checkcontentid' => 'checkcontentid',
            'orderid' => 'orderid',
            'title' => 'title',
            'duid' => 'duid',
            'dnick' => 'dnick',
            'allprice' => 'allprice',
            'commission' => 'commission',
            'stime' => 'stime',
            'myfromname' => 'myfromname'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_checkorder';
    }

}
