<?php

/**
 * WeChangeBatch
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:51
 */
class WeChangeBatch extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $old_goodsid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $old_goodstitle;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $old_goodsisgroup;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $old_goods_mygroup;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $new_goodsid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $new_goodstitle;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $new_goodsisgroup;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $new_goods_mygroup;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $duid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $stimeint;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $change_door_num;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $hasgoods_door_num;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $nogoods_door_num;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $change_info;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeChangeBatch[]|WeChangeBatch|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeChangeBatch|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'comid' => 'comid',
            'old_goodsid' => 'old_goodsid',
            'old_goodstitle' => 'old_goodstitle',
            'old_goodsisgroup' => 'old_goodsisgroup',
            'old_goods_mygroup' => 'old_goods_mygroup',
            'new_goodsid' => 'new_goodsid',
            'new_goodstitle' => 'new_goodstitle',
            'new_goodsisgroup' => 'new_goodsisgroup',
            'new_goods_mygroup' => 'new_goods_mygroup',
            'duid' => 'duid',
            'stimeint' => 'stimeint',
            'change_door_num' => 'change_door_num',
            'hasgoods_door_num' => 'hasgoods_door_num',
            'nogoods_door_num' => 'nogoods_door_num',
            'change_info' => 'change_info'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_change_batch';
    }

}
