<?php

/**
 * WeCheck
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:51
 */
class WeCheck extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $uid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_gic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $duid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $myvalue;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $mystatus;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $stimeint;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $fullname;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $payname;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $paybank;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $payaccount;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $other;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $moneycomidlist;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $starttime;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $endtime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $starttimeint;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $endtimeint;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $comname;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $telfront;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $comic;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $dnick;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $takemoneyid;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeCheck[]|WeCheck|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeCheck|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'uid' => 'uid',
            'comid' => 'comid',
            'u_gic' => 'u_gic',
            'duid' => 'duid',
            'myvalue' => 'myvalue',
            'mystatus' => 'mystatus',
            'stime' => 'stime',
            'stimeint' => 'stimeint',
            'fullname' => 'fullname',
            'payname' => 'payname',
            'paybank' => 'paybank',
            'payaccount' => 'payaccount',
            'other' => 'other',
            'moneycomidlist' => 'moneycomidlist',
            'starttime' => 'starttime',
            'endtime' => 'endtime',
            'starttimeint' => 'starttimeint',
            'endtimeint' => 'endtimeint',
            'comname' => 'comname',
            'telfront' => 'telfront',
            'comic' => 'comic',
            'dnick' => 'dnick',
            'takemoneyid' => 'takemoneyid'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_check';
    }

}
