<?php

/**
 * WeChannel
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:51
 */
class WeChannel extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $ic;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mytip;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mytitle;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mykeywords;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $mydescription;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $readme;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $content;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $cha_url;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $cha_dir;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $cha_set;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $cha_moduleid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $cha_module;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $cha_modulename;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $cha_count;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $cha_show;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $cha_opentype;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $cls;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $cha_type;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $cha_typename;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $cha_unit;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $isuse;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $cha_page;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $cha_style;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $cha_other;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $preimg;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $icanghost;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $mytype;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $cha_mdb;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeChannel[]|WeChannel|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeChannel|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'ic' => 'ic',
            'title' => 'title',
            'mytip' => 'mytip',
            'mytitle' => 'mytitle',
            'mykeywords' => 'mykeywords',
            'mydescription' => 'mydescription',
            'readme' => 'readme',
            'content' => 'content',
            'cha_url' => 'cha_url',
            'cha_dir' => 'cha_dir',
            'cha_set' => 'cha_set',
            'cha_moduleid' => 'cha_moduleid',
            'cha_module' => 'cha_module',
            'cha_modulename' => 'cha_modulename',
            'cha_count' => 'cha_count',
            'cha_show' => 'cha_show',
            'cha_opentype' => 'cha_opentype',
            'cls' => 'cls',
            'cha_type' => 'cha_type',
            'cha_typename' => 'cha_typename',
            'cha_unit' => 'cha_unit',
            'isuse' => 'isuse',
            'cha_page' => 'cha_page',
            'cha_style' => 'cha_style',
            'cha_other' => 'cha_other',
            'preimg' => 'preimg',
            'icanghost' => 'icanghost',
            'mytype' => 'mytype',
            'cha_mdb' => 'cha_mdb'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_channel';
    }

}
