<?php

/**
 * WeCheckcontent
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:52
 */
class WeCheckcontent extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $checkid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $xh;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $goodsid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $allprice;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $commission;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $ordernum;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $goodsnum;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $allcommission;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $orderlist;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mytype;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $check_type;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $comgoodsid;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeCheckcontent[]|WeCheckcontent|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeCheckcontent|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'checkid' => 'checkid',
            'xh' => 'xh',
            'goodsid' => 'goodsid',
            'allprice' => 'allprice',
            'commission' => 'commission',
            'ordernum' => 'ordernum',
            'goodsnum' => 'goodsnum',
            'allcommission' => 'allcommission',
            'orderlist' => 'orderlist',
            'title' => 'title',
            'mytype' => 'mytype',
            'check_type' => 'check_type',
            'comgoodsid' => 'comgoodsid'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_checkcontent';
    }

}
