<?php

/**
 * WeContact
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:54
 */
class WeContact extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $c_name;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $c_job;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $c_mobile;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    public $c_tel1a;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    public $c_tel1b;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    public $c_tel2a;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    public $c_tel2b;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $c_mail;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $classid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $title;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $cls;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $comtype;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeContact[]|WeContact|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeContact|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'c_name' => 'c_name',
            'c_job' => 'c_job',
            'c_mobile' => 'c_mobile',
            'c_tel1a' => 'c_tel1a',
            'c_tel1b' => 'c_tel1b',
            'c_tel2a' => 'c_tel2a',
            'c_tel2b' => 'c_tel2b',
            'c_mail' => 'c_mail',
            'comid' => 'comid',
            'classid' => 'classid',
            'title' => 'title',
            'cls' => 'cls',
            'comtype' => 'comtype'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_contact';
    }

}
