<?php

/**
 * WeCoupon
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:55
 */
class WeCoupon extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=10, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $title;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $useBeginTime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $useEndTime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $doUserId;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $doTime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $useType;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $money;

    /**
     *
     * @var integer
     * @Column(type="integer", length=255, nullable=true)
     */
    public $discount;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $useOtherNum;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $goodsid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $comgoodsid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $useMinMoney;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $comids;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $maxNum;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $comTake;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $status;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeCoupon[]|WeCoupon|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeCoupon|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'title' => 'title',
            'useBeginTime' => 'useBeginTime',
            'useEndTime' => 'useEndTime',
            'doUserId' => 'doUserId',
            'doTime' => 'doTime',
            'useType' => 'useType',
            'money' => 'money',
            'discount' => 'discount',
            'useOtherNum' => 'useOtherNum',
            'goodsid' => 'goodsid',
            'comgoodsid' => 'comgoodsid',
            'useMinMoney' => 'useMinMoney',
            'comids' => 'comids',
            'maxNum' => 'maxNum',
            'comTake' => 'comTake',
            'status' => 'status'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_coupon';
    }

}
