<?php

/**
 * WeCouponDetail
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:55
 */
class WeCouponDetail extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=10, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    public $couponId;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    public $code;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    public $userId;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    public $getTime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $isUsed;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $useTime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $takeMoney;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $ActivityIc;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeCouponDetail[]|WeCouponDetail|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeCouponDetail|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'couponId' => 'couponId',
            'code' => 'code',
            'userId' => 'userId',
            'getTime' => 'getTime',
            'isUsed' => 'isUsed',
            'useTime' => 'useTime',
            'takeMoney' => 'takeMoney',
            'ActivityIc' => 'ActivityIc'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_coupon_detail';
    }

}
