<?php

/**
 * WeComReplenishVmomey
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:53
 */
class WeComReplenishVmomey extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Column(type="integer", length=11, nullable=false)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $take_replenish_vmomey;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $money_precent;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $min_money;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $max_limit_time;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeComReplenishVmomey[]|WeComReplenishVmomey|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeComReplenishVmomey|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'comid' => 'comid',
            'take_replenish_vmomey' => 'take_replenish_vmomey',
            'money_precent' => 'money_precent',
            'min_money' => 'min_money',
            'max_limit_time' => 'max_limit_time'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_com_replenish_vmomey';
    }

}
