<?php

/**
 * WeDevice
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:56
 */
class WeDevice extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $ic;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $typeic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $doornum;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $goodsnum;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $isrun;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $placeic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $placeid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $comic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $stimeint;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mystatus;

    /**
     *
     * @var string
     * @Column(type="string", length=15, nullable=true)
     */
    public $serverip;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeDevice[]|WeDevice|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeDevice|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'ic' => 'ic',
            'typeic' => 'typeic',
            'doornum' => 'doornum',
            'goodsnum' => 'goodsnum',
            'isrun' => 'isrun',
            'placeic' => 'placeic',
            'placeid' => 'placeid',
            'comid' => 'comid',
            'comic' => 'comic',
            'stimeint' => 'stimeint',
            'mystatus' => 'mystatus',
            'serverip' => 'serverip'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_device';
    }

}
