<?php

/**
 * WeDoor
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:56
 */
class WeDoor extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $ic;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $title;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $hasgoods;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mystatus;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $doorstatus;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $deviceid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $deviceic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $comgoodsid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $goodsid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $goodsic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $placeid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $ischange;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $com_can_change_goods;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeDoor[]|WeDoor|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeDoor|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'ic' => 'ic',
            'title' => 'title',
            'hasgoods' => 'hasgoods',
            'mystatus' => 'mystatus',
            'doorstatus' => 'doorstatus',
            'deviceid' => 'deviceid',
            'deviceic' => 'deviceic',
            'comgoodsid' => 'comgoodsid',
            'goodsid' => 'goodsid',
            'goodsic' => 'goodsic',
            'comid' => 'comid',
            'placeid' => 'placeid',
            'ischange' => 'ischange',
            'com_can_change_goods' => 'com_can_change_goods'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_door';
    }

}
