<?php

/**
 * WeFailtofix
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:57
 */
class WeFailtofix extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $comname;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $address;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $tel;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $building;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $floor;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $deviceic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $door;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $type;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $status;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $isend;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $cal;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $stimeint;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $repairtime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $placeid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mytype;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mytypename;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $repairtimeint;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $ischange;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $goodstitle;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeFailtofix[]|WeFailtofix|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeFailtofix|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'comname' => 'comname',
            'address' => 'address',
            'tel' => 'tel',
            'building' => 'building',
            'floor' => 'floor',
            'title' => 'title',
            'deviceic' => 'deviceic',
            'door' => 'door',
            'type' => 'type',
            'status' => 'status',
            'isend' => 'isend',
            'cal' => 'cal',
            'stime' => 'stime',
            'stimeint' => 'stimeint',
            'repairtime' => 'repairtime',
            'comid' => 'comid',
            'placeid' => 'placeid',
            'mytype' => 'mytype',
            'mytypename' => 'mytypename',
            'repairtimeint' => 'repairtimeint',
            'ischange' => 'ischange',
            'goodstitle' => 'goodstitle'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_failtofix';
    }

}
