<?php

/**
 * WeForm
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:57
 */
class WeForm extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $ic;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $aic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $readme;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $myvalue;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $mycount;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $questioncount;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $plantime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $donecount;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $suid;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $stimeint;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $overtime;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $mystatus;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $openness;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $getgrant;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeForm[]|WeForm|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeForm|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'ic' => 'ic',
            'aic' => 'aic',
            'comid' => 'comid',
            'title' => 'title',
            'readme' => 'readme',
            'myvalue' => 'myvalue',
            'mycount' => 'mycount',
            'questioncount' => 'questioncount',
            'plantime' => 'plantime',
            'donecount' => 'donecount',
            'suid' => 'suid',
            'stime' => 'stime',
            'stimeint' => 'stimeint',
            'overtime' => 'overtime',
            'mystatus' => 'mystatus',
            'openness' => 'openness',
            'getgrant' => 'getgrant'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_form';
    }

}
