<?php

/**
 * WeFormRenshou1
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:57
 */
class WeFormRenshou1 extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $formid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $uid;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $stimeint;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $f_fullname;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $f_mobile;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $f_age;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $f_marriage;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $f_car;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeFormRenshou1[]|WeFormRenshou1|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeFormRenshou1|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'formid' => 'formid',
            'uid' => 'uid',
            'stime' => 'stime',
            'stimeint' => 'stimeint',
            'f_fullname' => 'f_fullname',
            'f_mobile' => 'f_mobile',
            'f_age' => 'f_age',
            'f_marriage' => 'f_marriage',
            'f_car' => 'f_car'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_form_renshou1';
    }

}
