<?php

/**
 * WeFrontSellOrder
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:58
 */
class WeFrontSellOrder extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=10, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    public $uid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    public $order_money;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    public $supply_money;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $order_notes;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $sell_detail;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $create_time;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeFrontSellOrder[]|WeFrontSellOrder|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeFrontSellOrder|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'uid' => 'uid',
            'comid' => 'comid',
            'order_money' => 'order_money',
            'supply_money' => 'supply_money',
            'order_notes' => 'order_notes',
            'sell_detail' => 'sell_detail',
            'create_time' => 'create_time'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_front_sell_order';
    }

}
