<?php

/**
 * WeHelp
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:00
 */
class WeHelp extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $cid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $cic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $classid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $classname;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $suid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $snick;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $ptime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $euid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $enick;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $etime;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=false)
     */
    public $readme;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $preimg;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $mycontent;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $mycontentnojs;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $mytip;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $mytitle;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $mykeywords;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=false)
     */
    public $mydescription;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $cls;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $isgood;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $hits;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $isshow;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $isdel;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeHelp[]|WeHelp|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeHelp|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'cid' => 'cid',
            'cic' => 'cic',
            'classid' => 'classid',
            'classname' => 'classname',
            'suid' => 'suid',
            'snick' => 'snick',
            'stime' => 'stime',
            'ptime' => 'ptime',
            'euid' => 'euid',
            'enick' => 'enick',
            'etime' => 'etime',
            'title' => 'title',
            'readme' => 'readme',
            'preimg' => 'preimg',
            'mycontent' => 'mycontent',
            'mycontentnojs' => 'mycontentnojs',
            'mytip' => 'mytip',
            'mytitle' => 'mytitle',
            'mykeywords' => 'mykeywords',
            'mydescription' => 'mydescription',
            'cls' => 'cls',
            'isgood' => 'isgood',
            'hits' => 'hits',
            'isshow' => 'isshow',
            'isdel' => 'isdel'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_help';
    }

}
