<?php

/**
 * WeHotelorder
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:00
 */
class WeHotelorder extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $uid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $unick;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $stimeint;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $euid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $eunick;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $etimeint;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $etime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $isdel;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $mydate1;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $mydate2;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $roomid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $roomname;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $hotelid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $hotelname;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $roomcount;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $allprice;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $favorprice;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $payprice;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $guestinfo;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $actualprice;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $dofavorprice;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $everyprice;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $dayfavorprice;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $isspecial;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $abiz;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $guestmobile;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $guestmail;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $arrivetime1;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $arrivetime2;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $mystatus;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $mystatusname;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $paytype;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $paytypename;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $payway;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $ispayed;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $payid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $makingcard;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $makingtime;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $madecodelist;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $livecount;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $retrievingcard;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $retrievtime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $ismadecard;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $roomcode;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $roomcodeid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $roomtitle;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $islockcode;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $iscontinuelive;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $continuelivecode;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $bywho;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $mydate1a;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $mydate2a;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $bizjudge;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $bizjudgetime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $bizjudgetimeint;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $userjudge;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $judgedetail;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $isaccess;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $order_sources;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeHotelorder[]|WeHotelorder|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeHotelorder|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'uid' => 'uid',
            'unick' => 'unick',
            'stimeint' => 'stimeint',
            'stime' => 'stime',
            'euid' => 'euid',
            'eunick' => 'eunick',
            'etimeint' => 'etimeint',
            'etime' => 'etime',
            'isdel' => 'isdel',
            'mydate1' => 'mydate1',
            'mydate2' => 'mydate2',
            'roomid' => 'roomid',
            'roomname' => 'roomname',
            'hotelid' => 'hotelid',
            'hotelname' => 'hotelname',
            'roomcount' => 'roomcount',
            'allprice' => 'allprice',
            'favorprice' => 'favorprice',
            'payprice' => 'payprice',
            'guestinfo' => 'guestinfo',
            'actualprice' => 'actualprice',
            'dofavorprice' => 'dofavorprice',
            'everyprice' => 'everyprice',
            'dayfavorprice' => 'dayfavorprice',
            'isspecial' => 'isspecial',
            'abiz' => 'abiz',
            'guestmobile' => 'guestmobile',
            'guestmail' => 'guestmail',
            'arrivetime1' => 'arrivetime1',
            'arrivetime2' => 'arrivetime2',
            'mystatus' => 'mystatus',
            'mystatusname' => 'mystatusname',
            'paytype' => 'paytype',
            'paytypename' => 'paytypename',
            'payway' => 'payway',
            'ispayed' => 'ispayed',
            'payid' => 'payid',
            'makingcard' => 'makingcard',
            'makingtime' => 'makingtime',
            'madecodelist' => 'madecodelist',
            'livecount' => 'livecount',
            'retrievingcard' => 'retrievingcard',
            'retrievtime' => 'retrievtime',
            'ismadecard' => 'ismadecard',
            'roomcode' => 'roomcode',
            'roomcodeid' => 'roomcodeid',
            'roomtitle' => 'roomtitle',
            'islockcode' => 'islockcode',
            'iscontinuelive' => 'iscontinuelive',
            'continuelivecode' => 'continuelivecode',
            'bywho' => 'bywho',
            'mydate1a' => 'mydate1a',
            'mydate2a' => 'mydate2a',
            'bizjudge' => 'bizjudge',
            'bizjudgetime' => 'bizjudgetime',
            'bizjudgetimeint' => 'bizjudgetimeint',
            'userjudge' => 'userjudge',
            'judgedetail' => 'judgedetail',
            'isaccess' => 'isaccess',
            'order_sources' => 'order_sources'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_hotelorder';
    }

}
