<?php

/**
 * WeJoinusform
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:00
 */
class WeJoinusform extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $f_name;

    /**
     *
     * @var string
     * @Column(type="string", length=11, nullable=true)
     */
    public $f_mobile;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $f_field;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $f_message;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $stimeint;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeJoinusform[]|WeJoinusform|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeJoinusform|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'f_name' => 'f_name',
            'f_mobile' => 'f_mobile',
            'f_field' => 'f_field',
            'f_message' => 'f_message',
            'stime' => 'stime',
            'stimeint' => 'stimeint'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_joinusform';
    }

}
