<?php

/**
 * WeLogin
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:01
 */
class WeLogin extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $u_id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_name;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_nick;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_pass;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_ip;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $stime;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $mysource;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeLogin[]|WeLogin|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeLogin|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'u_id' => 'u_id',
            'u_name' => 'u_name',
            'u_nick' => 'u_nick',
            'u_pass' => 'u_pass',
            'u_ip' => 'u_ip',
            'stime' => 'stime',
            'mysource' => 'mysource',
            'comid' => 'comid'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_login';
    }

}
