<?php

/**
 * WeMarketingActivity
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:02
 */
class WeMarketingActivity extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $act_title;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $act_ic;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $time_start;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $time_start_int;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $time_end;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $time_end_int;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $act_status;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $send_type;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    public $act_user;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $act_com;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $time_add;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $time_edit;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeMarketingActivity[]|WeMarketingActivity|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeMarketingActivity|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'act_title' => 'act_title',
            'act_ic' => 'act_ic',
            'time_start' => 'time_start',
            'time_start_int' => 'time_start_int',
            'time_end' => 'time_end',
            'time_end_int' => 'time_end_int',
            'act_status' => 'act_status',
            'send_type' => 'send_type',
            'act_user' => 'act_user',
            'act_com' => 'act_com',
            'time_add' => 'time_add',
            'time_edit' => 'time_edit'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_marketing_activity';
    }

}
