<?php

/**
 * WeMenu
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:03
 */
class WeMenu extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $titlecode;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $url;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $para;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $pid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $idpath;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $power;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $cls;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $cid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $plusid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $menuid;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeMenu[]|WeMenu|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeMenu|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'title' => 'title',
            'titlecode' => 'titlecode',
            'url' => 'url',
            'para' => 'para',
            'pid' => 'pid',
            'idpath' => 'idpath',
            'power' => 'power',
            'cls' => 'cls',
            'cid' => 'cid',
            'plusid' => 'plusid',
            'menuid' => 'menuid'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_menu';
    }

}
