<?php

/**
 * WeMoneysetting
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:04
 */
class WeMoneysetting extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $ic;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $readme;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $pid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $cls;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $mytype;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $mytypename;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $opuser;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $opbiz;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $opplat;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeMoneysetting[]|WeMoneysetting|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeMoneysetting|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'ic' => 'ic',
            'title' => 'title',
            'readme' => 'readme',
            'pid' => 'pid',
            'cls' => 'cls',
            'mytype' => 'mytype',
            'mytypename' => 'mytypename',
            'opuser' => 'opuser',
            'opbiz' => 'opbiz',
            'opplat' => 'opplat'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_moneysetting';
    }

}
