<?php

/**
 * WeOrdergoods
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:07
 */
class WeOrdergoods extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $orderid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $title;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $allprice;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $goodsid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comgoodsid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $preimg;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $placeid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $deviceid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $doorid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $mystatus;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $counts;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $doortitle;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    public $door_num;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $order_type;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $act_goodsid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $commission;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $couponIds;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $couponPrice;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $couponInfo;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeOrdergoods[]|WeOrdergoods|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeOrdergoods|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'orderid' => 'orderid',
            'title' => 'title',
            'price' => 'price',
            'allprice' => 'allprice',
            'goodsid' => 'goodsid',
            'comgoodsid' => 'comgoodsid',
            'comid' => 'comid',
            'preimg' => 'preimg',
            'placeid' => 'placeid',
            'deviceid' => 'deviceid',
            'doorid' => 'doorid',
            'mystatus' => 'mystatus',
            'counts' => 'counts',
            'doortitle' => 'doortitle',
            'door_num' => 'door_num',
            'order_type' => 'order_type',
            'act_goodsid' => 'act_goodsid',
            'commission' => 'commission',
            'couponIds' => 'couponIds',
            'couponPrice' => 'couponPrice',
            'couponInfo' => 'couponInfo'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_ordergoods';
    }

}
