<?php

/**
 * WeOrderSend
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:06
 */
class WeOrderSend extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $orderid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $uid_send;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $uname_send;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $uid_accept;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $uname_accept;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $time_send;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $time_accept;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $type_send;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $method_send;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $send_code;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeOrderSend[]|WeOrderSend|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeOrderSend|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'orderid' => 'orderid',
            'uid_send' => 'uid_send',
            'uname_send' => 'uname_send',
            'uid_accept' => 'uid_accept',
            'uname_accept' => 'uname_accept',
            'time_send' => 'time_send',
            'time_accept' => 'time_accept',
            'type_send' => 'type_send',
            'method_send' => 'method_send',
            'send_code' => 'send_code'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_order_send';
    }

}
