<?php

/**
 * WeOrderPay
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:06
 */
class WeOrderPay extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $allprice;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $yue_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $zengkuan_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $coupon_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $other_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $service_price;

    /**
     *
     * @var string
     * @Column(type="string", length=30, nullable=true)
     */
    public $payway;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $stimeint;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $ispayed;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime_pay;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=true)
     */
    public $pay_code;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeOrderPay[]|WeOrderPay|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeOrderPay|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'allprice' => 'allprice',
            'yue_price' => 'yue_price',
            'zengkuan_price' => 'zengkuan_price',
            'coupon_price' => 'coupon_price',
            'other_price' => 'other_price',
            'service_price' => 'service_price',
            'payway' => 'payway',
            'stime' => 'stime',
            'stimeint' => 'stimeint',
            'ispayed' => 'ispayed',
            'stime_pay' => 'stime_pay',
            'pay_code' => 'pay_code'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_order_pay';
    }

}
