<?php


namespace Common\Models;

/**
 * WeOrder
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:06
 */
class WeOrder extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=true)
     */
    public $pay_code;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $allprice;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $yue_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $zengkuan_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $other_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $service_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $coupon_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $commission;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $stimeint;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $uid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $ispayed;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mystatus;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $gids;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $payway;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $placeid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $mytype;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $doorids;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $deviceid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $comgoodsids;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $doorstatus;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $mygoods;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $paytimeint;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $alllocker;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $goodlocker;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $badlocker;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $order_type;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $door_num;

    /**
     *
     * @var integer
     * @Column(type="integer", length=2, nullable=true)
     */
    public $floor;

    /**
     *
     * @var integer
     * @Column(type="integer", length=2, nullable=true)
     */
    public $isdel;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $des;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $act_id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $act_goodsid;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeOrder[]|WeOrder|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeOrder|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'pay_code' => 'pay_code',
            'allprice' => 'allprice',
            'yue_price' => 'yue_price',
            'zengkuan_price' => 'zengkuan_price',
            'other_price' => 'other_price',
            'service_price' => 'service_price',
            'coupon_price' => 'coupon_price',
            'commission' => 'commission',
            'stime' => 'stime',
            'stimeint' => 'stimeint',
            'uid' => 'uid',
            'ispayed' => 'ispayed',
            'mystatus' => 'mystatus',
            'gids' => 'gids',
            'payway' => 'payway',
            'comid' => 'comid',
            'placeid' => 'placeid',
            'mytype' => 'mytype',
            'doorids' => 'doorids',
            'deviceid' => 'deviceid',
            'comgoodsids' => 'comgoodsids',
            'doorstatus' => 'doorstatus',
            'mygoods' => 'mygoods',
            'paytimeint' => 'paytimeint',
            'alllocker' => 'alllocker',
            'goodlocker' => 'goodlocker',
            'badlocker' => 'badlocker',
            'order_type' => 'order_type',
            'door_num' => 'door_num',
            'floor' => 'floor',
            'isdel' => 'isdel',
            'des' => 'des',
            'act_id' => 'act_id',
            'act_goodsid' => 'act_goodsid'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_order';
    }

}
