<?php

/**
 * WePassword
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:07
 */
class WePassword extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $rand_code;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $hotelid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $uid;

    /**
     *
     * @var string
     * @Column(type="string", length=30, nullable=true)
     */
    public $u_mobile;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $etime;

    /**
     *
     * @var string
     * @Column(type="string", length=250, nullable=true)
     */
    public $pass_url;

    /**
     *
     * @var string
     * @Column(type="string", length=30, nullable=true)
     */
    public $u_mail;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $mailbody;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $myip;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $isone;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $rand;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    public $sendform;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WePassword[]|WePassword|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WePassword|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'rand_code' => 'rand_code',
            'hotelid' => 'hotelid',
            'uid' => 'uid',
            'u_mobile' => 'u_mobile',
            'stime' => 'stime',
            'etime' => 'etime',
            'pass_url' => 'pass_url',
            'u_mail' => 'u_mail',
            'title' => 'title',
            'mailbody' => 'mailbody',
            'myip' => 'myip',
            'isone' => 'isone',
            'rand' => 'rand',
            'sendform' => 'sendform'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_password';
    }

}
