<?php

/**
 * WePlace
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:07
 */
class WePlace extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $ic;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $building;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $floor;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $comid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $comic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $cls;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $isdel;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WePlace[]|WePlace|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WePlace|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'ic' => 'ic',
            'title' => 'title',
            'building' => 'building',
            'floor' => 'floor',
            'comid' => 'comid',
            'comic' => 'comic',
            'cls' => 'cls',
            'isdel' => 'isdel'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_place';
    }

}
