<?php

/**
 * WeSendmail
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:08
 */
class WeSendmail extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $sendmail;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $frommail;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $fromname;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $sendsubject;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $sendmsg;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $sendip;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $sendtime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $sendtimeint;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $senduid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $sendduid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $others;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeSendmail[]|WeSendmail|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeSendmail|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'sendmail' => 'sendmail',
            'frommail' => 'frommail',
            'fromname' => 'fromname',
            'sendsubject' => 'sendsubject',
            'sendmsg' => 'sendmsg',
            'sendip' => 'sendip',
            'sendtime' => 'sendtime',
            'sendtimeint' => 'sendtimeint',
            'senduid' => 'senduid',
            'sendduid' => 'sendduid',
            'others' => 'others'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_sendmail';
    }

}
