<?php

/**
 * WeSpecialroomlist
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:09
 */
class WeSpecialroomlist extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $hotelid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $hotelname;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $roomid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $roomname;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $mydate;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $mydatefm;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $roomsupply;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $roomremain;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $roomorder;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $roomselled;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $roomsum;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $isopen;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $price10;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $price20;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $price30;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $savetime1;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $savetime2;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $mystatus;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeSpecialroomlist[]|WeSpecialroomlist|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeSpecialroomlist|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'hotelid' => 'hotelid',
            'hotelname' => 'hotelname',
            'roomid' => 'roomid',
            'roomname' => 'roomname',
            'mydate' => 'mydate',
            'mydatefm' => 'mydatefm',
            'roomsupply' => 'roomsupply',
            'roomremain' => 'roomremain',
            'roomorder' => 'roomorder',
            'roomselled' => 'roomselled',
            'roomsum' => 'roomsum',
            'isopen' => 'isopen',
            'price10' => 'price10',
            'price20' => 'price20',
            'price30' => 'price30',
            'price' => 'price',
            'savetime1' => 'savetime1',
            'savetime2' => 'savetime2',
            'mystatus' => 'mystatus'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_specialroomlist';
    }

}
