<?php

/**
 * WeSpecial
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:09
 */
class WeSpecial extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $cid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $tip;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $content;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $preimg;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $readme;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $cls;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $isgood;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $isopen;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mytitle;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mykeywords;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $mydescription;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $myurl;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $idlist;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeSpecial[]|WeSpecial|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeSpecial|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'cid' => 'cid',
            'title' => 'title',
            'tip' => 'tip',
            'content' => 'content',
            'preimg' => 'preimg',
            'readme' => 'readme',
            'cls' => 'cls',
            'isgood' => 'isgood',
            'isopen' => 'isopen',
            'mytitle' => 'mytitle',
            'mykeywords' => 'mykeywords',
            'mydescription' => 'mydescription',
            'myurl' => 'myurl',
            'idlist' => 'idlist'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_special';
    }

}
