<?php

/**
 * WeStoreBatch
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:10
 */
class WeStoreBatch extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $stimeint;

    /**
     *
     * @var string
     * @Column(type="string", length=30, nullable=false)
     */
    public $formcode;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $duid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $status;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $ruid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $rtimeint;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $isdel;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $other;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $storefrom;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $storeto;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $type_count;

    /**
     *
     * @var integer
     * @Column(type="integer", length=5, nullable=true)
     */
    public $storefrom_front_cnt;

    /**
     *
     * @var integer
     * @Column(type="integer", length=5, nullable=true)
     */
    public $storeto_front_cnt;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeStoreBatch[]|WeStoreBatch|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeStoreBatch|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'comid' => 'comid',
            'stimeint' => 'stimeint',
            'formcode' => 'formcode',
            'duid' => 'duid',
            'status' => 'status',
            'ruid' => 'ruid',
            'rtimeint' => 'rtimeint',
            'isdel' => 'isdel',
            'other' => 'other',
            'storefrom' => 'storefrom',
            'storeto' => 'storeto',
            'type_count' => 'type_count',
            'storefrom_front_cnt' => 'storefrom_front_cnt',
            'storeto_front_cnt' => 'storeto_front_cnt'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_store_batch';
    }

}
