<?php

/**
 * WeStoreFront
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:10
 */
class WeStoreFront extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $goodsid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comgoodsid;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=true)
     */
    public $formcode;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $duid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $stimeint;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $mycount;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $mytype;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $other;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $store_batch_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $status;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeStoreFront[]|WeStoreFront|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeStoreFront|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'goodsid' => 'goodsid',
            'comgoodsid' => 'comgoodsid',
            'formcode' => 'formcode',
            'duid' => 'duid',
            'stimeint' => 'stimeint',
            'mycount' => 'mycount',
            'mytype' => 'mytype',
            'other' => 'other',
            'comid' => 'comid',
            'store_batch_id' => 'store_batch_id',
            'status' => 'status'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_store_front';
    }

}
