<?php

/**
 * WeUplist
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:11
 */
class WeUplist extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $ftype;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $fid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $uid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_nick;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $myclassid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $rootid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $urlfile;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $urlthumb;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $utype;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $filesize;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $ufilewidth;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $ufileheight;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $isdel;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $mytype;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $fic;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeUplist[]|WeUplist|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeUplist|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'ftype' => 'ftype',
            'fid' => 'fid',
            'uid' => 'uid',
            'u_nick' => 'u_nick',
            'comid' => 'comid',
            'myclassid' => 'myclassid',
            'rootid' => 'rootid',
            'title' => 'title',
            'urlfile' => 'urlfile',
            'urlthumb' => 'urlthumb',
            'utype' => 'utype',
            'filesize' => 'filesize',
            'ufilewidth' => 'ufilewidth',
            'ufileheight' => 'ufileheight',
            'isdel' => 'isdel',
            'stime' => 'stime',
            'mytype' => 'mytype',
            'fic' => 'fic'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_uplist';
    }

}
