<?php

/**
 * WeUploaduser
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:11
 */
class WeUploaduser extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $u_mobile;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $u_nick;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $u_pass;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $u_idcode;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $stimeint;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $hotelid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $hoteltitle;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $suid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $snick;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $randcode;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $iseffect;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeUploaduser[]|WeUploaduser|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeUploaduser|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'u_mobile' => 'u_mobile',
            'u_nick' => 'u_nick',
            'u_pass' => 'u_pass',
            'u_idcode' => 'u_idcode',
            'stimeint' => 'stimeint',
            'stime' => 'stime',
            'hotelid' => 'hotelid',
            'hoteltitle' => 'hoteltitle',
            'suid' => 'suid',
            'snick' => 'snick',
            'randcode' => 'randcode',
            'iseffect' => 'iseffect'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_uploaduser';
    }

}
