<?php
/**
 * Created by PhpStorm.
 * User: wyd
 * Date: 2017-06-21
 * Time: 10:07
 */
?>


<form action="<?php echo $this->url->get('goods/add') ?>" method="post" id="editGoods">
    <?php echo $goodForm->render('id') ?>
    <br/>
    <?php echo $goodForm->render('title') ?> <br/>
    <?php echo $goodForm->render('ic') ?> <br/>
    <?php echo $goodForm->render('content') ?> <br/>
    <input type="submit" value="ok">
</form>
<script>
    $("#editGoods").on('submit', function (e) {
        e.preventDefault();
        helper.submitByAjax(this, function (json) {
            /*表格重载*/
            dataGridHelper.gridSelectorAll['grid-table'].trigger("reloadGrid");
            bootbox.confirm({
                message: json.msg,
                buttons: {
                    confirm: {label: '继续编辑', className: 'btn-success'},
                    cancel: {label: '关闭', className: 'btn-danger'}
                },
                callback: function (result) {
                    if (!result) {
                        /*关闭dialog*/
                        var dialogId = $('#editGoods').parent().attr('id');
                        $("#" + dialogId).dialog('close');
                    }
                }
            });


        });
        return false;
    });
</script>

