<?php
namespace Common\Models;
/**
 * WeComgoods
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:53
 */
class WeComgoods extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $goodsid;

    /**
     *
     * @var string
     * @Column(type="string", length=30, nullable=true)
     */
    public $goodsic;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $commission;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $inventories;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $inventoriesalarm;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $supply_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $sale_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $sale_commission;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $isdel;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $inventories_store;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $inventories_front;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $inventories_sd;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=true)
     */
    public $cls;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $status;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $type;
    protected $aaaaa;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->hasOne('goodsid','Common\Models\WeGoods','id',['alias'=>'goods']);
//        $this->hasMany('goodsid','Common\Models\WeGoods','id',['alias'=>'goods']);
//        $this->hasManyToMany("id",
//                 "Common\Models\WeGoods",
//                 "robots_id",
//                 "parts_id",
//                 "Parts",
//                 "id");
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeComgoods[]|WeComgoods|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeComgoods|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'goodsid' => 'goodsid',
            'goodsic' => 'goodsic',
            'price' => 'price',
            'commission' => 'commission',
            'comid' => 'comid',
            'inventories' => 'inventories',
            'inventoriesalarm' => 'inventoriesalarm',
            'supply_price' => 'supply_price',
            'sale_price' => 'sale_price',
            'sale_commission' => 'sale_commission',
            'isdel' => 'isdel',
            'inventories_store' => 'inventories_store',
            'inventories_front' => 'inventories_front',
            'inventories_sd' => 'inventories_sd',
            'cls' => 'cls',
            'status' => 'status',
            'type' => 'type'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_comgoods';
    }

}
