<?php
namespace Common\Models;
use \Phalcon\Validation;


/**
 * WeGoods
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:10:59
 */
class WeGoods extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $ic;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $preimg;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $bigimg;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $content;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $readme;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $isgroup;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $mygroup;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $inventories;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $inventoriessum;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $inventoriesalarm;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $salenum;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $base_price;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $sysbizer_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    public $isdel;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $class_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comClass_id;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {

        $this->setSchema("magiclamp");
    }

    public function validation()
    {
        $validator=new Validation();
        return $this->validate($validator);
    }
    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeGoods[]|WeGoods|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeGoods|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'ic' => 'ic',
            'title' => 'title',
            'preimg' => 'preimg',
            'bigimg' => 'bigimg',
            'content' => 'content',
            'readme' => 'readme',
            'comid' => 'comid',
            'isgroup' => 'isgroup',
            'mygroup' => 'mygroup',
            'inventories' => 'inventories',
            'inventoriessum' => 'inventoriessum',
            'inventoriesalarm' => 'inventoriesalarm',
            'salenum' => 'salenum',
            'base_price' => 'base_price',
            'sysbizer_id' => 'sysbizer_id',
            'isdel' => 'isdel',
            'class_id' => 'class_id',
            'comClass_id' => 'comClass_id'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_goods';
    }

}
