<?php
namespace Common\Models;
/**
 * WeUser
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-06-21, 07:11:11
 */
class WeUser extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $u_gic;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $u_gname;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $u_roleic;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $u_rolename;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_name;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $u_pass;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $u_paypwd;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $u_mail;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    public $u_gender;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_phone;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_mobile;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $u_face;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $u_regtimeint;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $u_regtime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $u_endtimeint;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $u_endtime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $u_point;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_nick;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_fullname;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $u_countshortmess;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $u_atime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $u_lastlogintime;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $u_blacklist;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $u_err;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $u_searchpasserr;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $u_searchpasserrtime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $stimeint;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $stime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $suid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $snick;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $etimeint;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $etime;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $euid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $enick;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $ischeck;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $islock;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $isdel;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_ip;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $u_online;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $u_ismaster;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $randcode;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $crandcode;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $hashotel;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $aall;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $acanuse;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $ain;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $aincome;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $aout;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $afrize;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $agiveprice;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $u_idcode;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $recommend_id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $recommend_nick;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $comid;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $comname;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $comisdel;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $u_payerr;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $firstorder;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $ischeckmail;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $isinfo;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=true)
     */
    public $u_source;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $creditlevel;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $level;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $u_grow;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $vmoney;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("magiclamp");
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeUser[]|WeUser|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return WeUser|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'u_gic' => 'u_gic',
            'u_gname' => 'u_gname',
            'u_roleic' => 'u_roleic',
            'u_rolename' => 'u_rolename',
            'u_name' => 'u_name',
            'u_pass' => 'u_pass',
            'u_paypwd' => 'u_paypwd',
            'u_mail' => 'u_mail',
            'u_gender' => 'u_gender',
            'u_phone' => 'u_phone',
            'u_mobile' => 'u_mobile',
            'u_face' => 'u_face',
            'u_regtimeint' => 'u_regtimeint',
            'u_regtime' => 'u_regtime',
            'u_endtimeint' => 'u_endtimeint',
            'u_endtime' => 'u_endtime',
            'u_point' => 'u_point',
            'u_nick' => 'u_nick',
            'u_fullname' => 'u_fullname',
            'u_countshortmess' => 'u_countshortmess',
            'u_atime' => 'u_atime',
            'u_lastlogintime' => 'u_lastlogintime',
            'u_blacklist' => 'u_blacklist',
            'u_err' => 'u_err',
            'u_searchpasserr' => 'u_searchpasserr',
            'u_searchpasserrtime' => 'u_searchpasserrtime',
            'stimeint' => 'stimeint',
            'stime' => 'stime',
            'suid' => 'suid',
            'snick' => 'snick',
            'etimeint' => 'etimeint',
            'etime' => 'etime',
            'euid' => 'euid',
            'enick' => 'enick',
            'ischeck' => 'ischeck',
            'islock' => 'islock',
            'isdel' => 'isdel',
            'u_ip' => 'u_ip',
            'u_online' => 'u_online',
            'u_ismaster' => 'u_ismaster',
            'randcode' => 'randcode',
            'crandcode' => 'crandcode',
            'hashotel' => 'hashotel',
            'aall' => 'aall',
            'acanuse' => 'acanuse',
            'ain' => 'ain',
            'aincome' => 'aincome',
            'aout' => 'aout',
            'afrize' => 'afrize',
            'agiveprice' => 'agiveprice',
            'u_idcode' => 'u_idcode',
            'recommend_id' => 'recommend_id',
            'recommend_nick' => 'recommend_nick',
            'comid' => 'comid',
            'comname' => 'comname',
            'comisdel' => 'comisdel',
            'u_payerr' => 'u_payerr',
            'firstorder' => 'firstorder',
            'ischeckmail' => 'ischeckmail',
            'isinfo' => 'isinfo',
            'u_source' => 'u_source',
            'creditlevel' => 'creditlevel',
            'level' => 'level',
            'u_grow' => 'u_grow',
            'vmoney' => 'vmoney'
        ];
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'we_user';
    }

}
