<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta charset="utf-8"/>
   <?php echo $this->tag->getTitle(); ?>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="<?= $assetUri ?>assets/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="<?= $assetUri ?>assets/font-awesome/4.5.0/css/font-awesome.min.css"/>

    <!-- page specific plugin styles -->
    <link rel="stylesheet" href="<?= $assetUri ?>assets/css/jquery-ui.min.css"/>
    <link rel="stylesheet" href="<?php echo $assetUri; ?>assets/css/ui.jqgrid.min.css"/>


    <!-- text fonts -->
    <link rel="stylesheet" href="<?= $assetUri ?>assets/css/fonts.googleapis.com.css"/>
    <!-- ace styles -->
    <link rel="stylesheet" href="<?= $assetUri ?>assets/css/ace.min.css" class="ace-main-stylesheet"
          id="main-ace-style"/>
    <!--[if lte IE 9]>
    <link rel="stylesheet" href="<?=$assetUri?>assets/css/ace-part2.min.css" class="ace-main-stylesheet"/>
    <![endif]-->
    <link rel="stylesheet" href="<?= $assetUri ?>assets/css/ace-skins.min.css"/>
    <link rel="stylesheet" href="<?= $assetUri ?>assets/css/ace-rtl.min.css"/>
    <!--[if lte IE 9]>
    <link rel="stylesheet" href="<?=$assetUri?>assets/css/ace-ie.min.css"/>
    <![endif]-->
    <!-- inline styles related to this page -->

    <!-- ace settings handler -->
    <script src="<?= $assetUri; ?>assets/js/ace-extra.min.js"></script>
    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->
    <!--[if lte IE 8]>
    <script src="<?=$assetUri; ?>assets/js/html5shiv.min.js"></script>
    <script src="<?=$assetUri; ?>assets/js/respond.min.js"></script>
    <![endif]-->
    <!--[if !IE]> -->
    <script src="<?= $assetUri; ?>assets/js/jquery-2.1.4.min.js"></script>
    <!-- <![endif]-->
    <!--[if IE]>
    <script src="<?=$assetUri; ?>assets/js/jquery-1.11.3.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        if ('ontouchstart' in document.documentElement) document.write("<script src='<?=$assetUri; ?>assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
    </script>
    <script src="<?= $assetUri; ?>assets/js/bootstrap.min.js"></script>
</head>
<body class="no-skin">
<!--顶部-->
<div id="navbar" class="navbar navbar-default ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <div class="navbar-header pull-left">
            <a href="<?= $assetUri ?>admin" class="navbar-brand">
                <small><i class="fa fa-leaf"></i><?= $projectTitle ?></small>
            </a>
        </div>

        <div class="navbar-buttons navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <li class="purple dropdown-modal">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="ace-icon fa fa-bell icon-animated-bell"></i>
                        <span class="badge badge-important">8</span>
                    </a>

                    <ul class="dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="ace-icon fa fa-exclamation-triangle"></i>
                            您有8条通知
                        </li>
                        <li class="dropdown-content">
                            <ul class="dropdown-menu dropdown-navbar navbar-pink">
                                <li>
                                    <a href="#">
                                        <div class="clearfix">
													<span class="pull-left">
														<i class="btn btn-xs no-hover btn-pink fa fa-comment"></i>
														系统更新
													</span>
                                            <span class="pull-right badge badge-info"></span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="clearfix">
													<span class="pull-left">
														<i class="btn btn-xs no-hover btn-info fa fa-twitter"></i>
														财务通知
													</span>
                                            <span class="pull-right badge badge-info"></span>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown-footer">
                            <a href="#">
                                查看更多通知
                                <i class="ace-icon fa fa-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="light-blue dropdown-modal">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img class="nav-user-photo" src="/assets/images/avatars/user.jpg" alt="Jason's Photo"/>
                        <span class="user-info"><small>欢迎光临</small>李雷</span>
                        <i class="ace-icon fa fa-caret-down"></i>
                    </a>
                    <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="#">
                                <i class="ace-icon fa fa-cog"></i>
                                个人信息
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <i class="ace-icon fa fa-power-off"></i>
                                退出登录
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.navbar-container -->
</div>
<!--//顶部-->


<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
        try {
            ace.settings.loadState('main-container')
        } catch (e) {
        }
    </script>
    <div id="sidebar" class="sidebar  responsive ace-save-state">
        <script type="text/javascript">
            try {
                ace.settings.loadState('sidebar')
            } catch (e) {
            }
        </script>
        <div class="sidebar-shortcuts" id="sidebar-shortcuts">
            <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
                <button class="btn btn-success">
                    <i class="ace-icon fa fa-signal"></i>
                </button>

                <button class="btn btn-info">
                    <i class="ace-icon fa fa-pencil"></i>
                </button>

                <button class="btn btn-warning">
                    <i class="ace-icon fa fa-users"></i>
                </button>

                <button class="btn btn-danger">
                    <i class="ace-icon fa fa-cogs"></i>
                </button>
            </div>
            <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
                <span class="btn btn-success"></span>

                <span class="btn btn-info"></span>

                <span class="btn btn-warning"></span>

                <span class="btn btn-danger"></span>
            </div>
        </div><!-- /.sidebar-shortcuts -->
        <?php include __DIR__ . '/layouts/menu.phtml'; ?>
        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
            <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state"
               data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>
    </div>
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="#">首页</a>
                    </li>
                    <?php if (!empty($breadCrumb) && is_array($breadCrumb)): ?>
                        <?php foreach ($breadCrumb as $key => $value): ?>
                            <?php if (empty($value['url'])): ?>
                                <li class="active"><?= $value['text'] ?></li>
                            <?php else: ?>
                                <li class="active"><a href="<?= $value['url'] ?>"><?= $value['text'] ?></a></li>
                            <?php endif ?>
                        <?php endforeach ?>
                    <?php endif ?>
                </ul><!-- /.breadcrumb -->
            </div>
            <?php echo $this->getcontent(); ?>
        </div>
    </div><!-- /.main-content -->

    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
                <span class="bigger-120"><span class="blue bolder">XXX</span>版权所有 &copy; 2013-2014</span>
            </div>
        </div>
    </div>
    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div><!-- /.main-container -->


<!--[if lte IE 8]>
<script src="<?= $assetUri; ?>assets/js/excanvas.min.js"></script>
<![endif]-->
<!--常用js-->
<script src="<?php echo $assetUri; ?>assets/js/bootbox.min.js"></script>
<script src="<?= $assetUri; ?>assets/js/jquery-ui.min.js"></script>
<script src="<?= $assetUri; ?>assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo $assetUri; ?>assets/js/jquery.validate.min.js"></script>
<script src="<?php echo $assetUri; ?>assets/js/jquery.validate_messages_cn.js"></script>
<script src="<?php echo $assetUri; ?>assets/js/jquery.ui.datepicker-zh-CN.js"></script>

<script src="<?php echo $assetUri; ?>assets/js/jquery.jqGrid.min.js"></script>
<script src="<?php echo $assetUri; ?>assets/js/grid.locale-zh.js"></script>
<script src="<?php echo $assetUri; ?>js/dataGridHelper.js"></script>

<script src="<?= $assetUri; ?>assets/js/ace-elements.min.js"></script>
<script src="<?= $assetUri; ?>assets/js/ace.min.js"></script>
<script src="<?= $assetUri; ?>js/helper.js"></script>
<!-- inline scripts related to this page -->

<script type="text/javascript">
    jQuery(function ($) {

    })
</script>
</body>
</html>
