<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>iview example</title>
    <link rel="stylesheet" type="text/css" href="/css/iview.css">
    <script type="text/javascript" src="/js/vue.min.js"></script>
    <script type="text/javascript" src="/js/iview.min.js"></script>
</head>
<body>
<div id="app">
    <i-button @click="show">Click me!</i-button>
    <Modal v-model="visible" title="Welcome">欢迎使用 iView</Modal>




</div>
<script>
    new Vue({
        el: '#app',
        data: {
            visible: false
            value:'sss'
        },
        methods: {
            show: function () {
                this.visible = true;
            }
        }
    })
</script>
</body>
</html>