<ul class="nav nav-list">
    <li class="active">
        <a>
            <i class="menu-icon fa fa-tachometer"></i>
            <span class="menu-text"> 控制面板 </span>
        </a>
        <b class="arrow"></b>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-desktop"></i>
            <span class="menu-text">商品信息</span>
            <b class="arrow fa fa-angle-down"></b>
        </a>
        <b class="arrow"></b>
        <ul class="submenu">
            <li class="">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-caret-right"></i>商品列表
                </a>
            </li>
            <li class="">
                <a href="#">
                    <i class="menu-icon fa fa-caret-right"></i>
                    添加商品
                </a>
            </li>
        </ul>
    </li>

    <li class="">
        <a href="#">
            <i class="menu-icon fa fa-calendar"></i>
            <span class="menu-text">财务管理
                <span class="badge badge-transparent tooltip-error" title="2 Important Events">
                    <i class="ace-icon fa fa-exclamation-triangle red bigger-130"></i>
                </span>
            </span>
        </a>
        <b class="arrow"></b>
    </li>
    <li class="">
        <a href="#">
            <i class="menu-icon fa fa-picture-o"></i>
            <span class="menu-text"> 日历 </span>
        </a>

        <b class="arrow"></b>
    </li>
    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-file-o"></i>
            <span class="menu-text">信息<span class="badge badge-primary">5</span></span>
            <b class="arrow fa fa-angle-down"></b>
        </a>
        <b class="arrow"></b>
        <ul class="submenu">
            <li class="">
                <a href="faq.html">
                    <i class="menu-icon fa fa-caret-right"></i>
                    未读信息
                </a>
                <b class="arrow"></b>
            </li>
            <li class="">
                <a href="error-404.html">
                    <i class="menu-icon fa fa-caret-right"></i>
                    通知信息
                </a>
                <b class="arrow"></b>
            </li>
            <li class="">
                <a href="error-500.html">
                    <i class="menu-icon fa fa-caret-right"></i>
                    警告信息
                </a>
                <b class="arrow"></b>
            </li>
            <li class="">
                <a href="grid.html">
                    <i class="menu-icon fa fa-caret-right"></i>
                    服务信息
                </a>
                <b class="arrow"></b>
            </li>

        </ul>
    </li>
</ul><!-- /.nav-list -->